### PR TITLE
Wii Remote info added

### PR DESCRIPTION
**Pull request by Raton-Laveur**
* Wii-Ext port is explained in system-specific page 
* Wii MotionPlus conflict resolution added to sync page

### CODE REVIEW

**Comment by darthcloud** [comment]
So motion-plus create problem in your experience?

I only tested the Wiimote with built-in motion plus and assumed external motion-plus behaved the same.

**Comment by Raton-Laveur** [comment]
Confirm - basic Wiimote with MotionPlus added disables attachments, and solution is to remove Wii MotionPlus. 
Could not confirm Wii Remote Plus, so thanks for confirming. Will add "Wii Remote Plus is fine though" in a future pull request.

**Comment by darthcloud** [comment]
For Wii motion stuff it's a bug so I wouldn't document it this way. Open a bug in main project and add the bug to the bug columns for Wii controller

**Comment by Raton-Laveur** [comment]
Okay, will rephrase current solution in another PR as a workaround: 1) remove Wii MotionPlus, or 2) use Wii Remote Plus

I assumed the Wii MotionPlus was pretty much a non-solvable issue, [considering the headaches it caused to document when it released](https://wiibrew.org/wiki/Wiimote/Extension_Controllers/Wii_Motion_Plus):  hence the "it's a conflict, just remove it" text.

Thanks!

**Comment by darthcloud** [comment]
I think the main problem is that specific wiibrew page is unreadable and I can't make much sense of it.

I lost mine so I ordered one and will check first hand.

Issues is now documented in https://github.com/darthcloud/BlueRetro/issues/612

So no need for another PR, I already added it to the table.

In general I don't want issue related stuff to spill in the docs.

**Pull request merged**
